### ISSUE TITLE
docs problems

### ISSUE THREAD

**Issue by fuckualreadytaken** [vectorgrp/sil-kit#1]
I found two docs problems when I try to start the demos.

1. In Ethernet Demo, the command of "System Controller" should be "build/Release/sil-kit-system-controller EthernetReader EthernetWriter", the docs is "build/Release/sil-kit-system-controller EthernetReader Ethernet Writer" 
2. In Lin Demo,  Step 1, I don't find the "NetworkSimulator" in the newest release files.

**Comment by MariusBgm** [comment]
@fuckualreadytaken  thanks for reporting these issues.
Regarding 1.), that's a typo and will be fixed, thx. The Idea is that the `sil-kit-system-controller` executable takes a space-separated list of participant names.

The `NetworkSimulator` is optional and not part of the sil-kit repository. 
You can just start the LIN Demo without it.
