### ISSUE TITLE
registryUri in participant configuration file

### ISSUE THREAD

**Issue by kocho1984** [vectorgrp/sil-kit#130]
Hi,

Is there a possibility to put registrUri in configuration file for the participant?

**Comment by kocho1984** [comment]
@MariusBgm, is there any easy way to get IP and listening port of sil-kit-registry from IParticipantConfiguration?
I have a config file with following entry and I would like to check in the code using SilKit API what IP and port is in the config.

Middleware:
  RegistryUri: silkit://55.55.55.55:8500

**Comment by VDanielEdwards** [comment]
Hello @kocho1984, no this is not possible. The configuration itself is a 'black box' for the application that loads / or uses it.

**Comment by VDanielEdwards** [comment]
If you don't mind me asking, what do you need the registry URI for?

**Comment by kocho1984** [comment]
I would like to check if IP is available and listening on that port. I have to do that before creating a participant.

**Comment by VDanielEdwards** [comment]
The connection to the registry is attempted during the call to `CreateParticipant`. If the connection fails, eg., if it runs into a timeout, or whatever is listening on the port isn't 'speaking' the SIL KIt network protocol like a HTTP server, an exception is thrown which you could catch.

**Comment by VDanielEdwards** [comment]
Additionally, SIL Kit will not just try to connect via TCP. At the moment we also attempt to connect via local-domain sockets using a 'predictable' name. But we might add further transports in the future, in addition to the existing ones.
