### ISSUE TITLE
Log file timestamp granularity

### ISSUE THREAD

**Issue by kocho1984** [vectorgrp/sil-kit#131]
Hi,

Could you please consider to change the format of a timestamp which is added to log file name? Currently, it has a second granularity.

What will happen if two participants that use the same config file are created at the same second? Will they share the same log file? I think that miliseconds granularity would be safer in such cases.

**Comment by VDanielEdwards** [comment]
Hello @kocho1984, thank you for posting this issue.

This is an issue that we have faced before as well, if multiple participants are started in the same process in quick succession. We've recently been discussing this internally.

**Comment by MariusBgm** [comment]
@kocho1984  @VDanielEdwards  I just merged something that should fix this issue temporarily: https://github.com/vectorgrp/sil-kit/pull/132 
We now add the participant's name to the log file's name.

**Comment by VDanielEdwards** [comment]
@kocho1984 and PR #132 has just been merged.
