### ISSUE TITLE
Why I do not see TCP traffic during the latency demo?

### ISSUE THREAD

**Issue by VladislavNeufeld** [vectorgrp/sil-kit#50]
Hello,

when I am running your latency demo and observing the TCP traffic with Wireshark I only see some increased traffic directly after starting of each .exe. But during the measurement (ping pong exchange of messages between sender and receiver) I don't see any TCP traffic. My expectation was that during that time there is the most traffic since messages are sent the whole time back and forth.
Could you please tell me what is wrong with my expectation?

BR

Vladislav

**Comment by VDanielEdwards** [comment]
Hello Vladislav, 

Thank you for your question!

SIL Kit generally tries to use local-domain sockets to communicate between participants.

However, it is possible to forbid participants from using local-domain sockets using the `EnableDomainSockets` key in the participant configuration. It is part of the `Middleware` block.

The configuration file [DemoBenchmarkDomainSocketsOff.silkit.yaml](https://github.com/vectorgrp/sil-kit/blob/main/Demos/Benchmark/DemoBenchmarkDomainSocketsOff.silkit.yaml) uses the option to turn them off.

Kind regards
Daniel

**Comment by VladislavNeufeld** [comment]
Thank You!
