### ISSUE TITLE
Missing documentation for SIL Kit Network Simulator on Flexray Demo

### ISSUE THREAD

**Issue by buihieu2005** [vectorgrp/sil-kit#8]
**Describe the issue**
In the Flexray Demo, there is no information about the SIL Kit network simulator.

**To Reproduce**
Steps to reproduce :
1. Go to Flexray Demo : https://vectorgrp.github.io/sil-kit-docs/usage/demos.html#flexray-demo
2.  Reading the requirements

**Expected behavior**
There are some explanation about:
- Role and responsible of SIL Kit network simulator 
- How to install and use it
- Info about the license 

**Screenshots**
NA

**Your Environment (please complete the following information):**
 - OS version and platform: Window 10
 - Compiler and CMake version: Visual Studio 16 2019
 - SIL Kit Version: 4.0.31

**Additional context**
I am experiencing about the Flexray communication with SIL KIt but I missing the information about the SIL Kit network simulator.

**Comment by MarcusEggenberger** [comment]
@buihieu2005: we have not yet made a public release of the SIL Kit network simulator. Let's continue this discussion by e-mail to find a suitable solution for you.

Thank you and best regards,
Marcus
