### ISSUE TITLE
program crashes without apparent reason when instantiating SilKit::Config::ParticipantConfigurationFromFile object

### ISSUE THREAD

**Issue by fskoras** [vectorgrp/sil-kit#9]
**Describe the issue**
I was trying to compile a simple example program from provided documentation "Developer Guide" chapter.
I am using vscode with cmake extension configuring visual studio 17 2022 toolchain

**To Reproduce**
follow the tutorial from documentation in specified environment

**Expected behavior**
I expect executable not to crash

**Screenshots**

CMakeLists.txt
---
![image](https://github.com/vectorgrp/sil-kit/assets/22472554/5c1ad4e1-644f-4dc5-88d7-e21625cd92e7)

simple.cpp
---
![image](https://github.com/vectorgrp/sil-kit/assets/22472554/4f7f260e-015c-44da-89b2-38890a9ccfab)

GDB output
---
![image](https://github.com/vectorgrp/sil-kit/assets/22472554/3672ab02-a74b-4724-a327-168eb7d59e92)

**Your Environment (please complete the following information):**
 - OS version: Windows 10
 - Compiler and CMake version: visual studio 17 2022, cmake version 3.28.0
 - SIL Kit Version: 4.0.43
 - Please include a description of the SIL Kit participants, including which
   controllers are created and the configuration applied to them: N/A

**Additional context**

When I try to compile the program with `config` object the program crash right after startup.
That means I am not even able to create a breakpoint in line 14 to see whats going on.

**Comment by MariusBgm** [comment]
Hi @fskoras , the Windows return code 0xC0000134 means DLL not found (STATUS_DLL_NOT_FOUND). When you run your sample exeucutable, make sure that you have SilKit.dll in the same folder, or the path containing it is in your PATH variable. That is not a crash in SilKit, it's Windows unable to load the dependencies. Hope that helps

**Comment by fskoras** [comment]
You are correct, that was it. I was just surprised I didn't receive any notification from the operating system that the dll failed to load. thank you for your help

**Comment by MariusBgm** [comment]
Great that it works for you. 
For what it's worth, If you start the executable in an explorer window you should get a pop-up dialog with an error message, if you run it in a shell or debugger, it doesn't show...
